# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api.divider_pb2 as divider__pb2


class DividerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Divide = channel.unary_unary(
                '/api.Divider/Divide',
                request_serializer=divider__pb2.DivideRequest.SerializeToString,
                response_deserializer=divider__pb2.DivideResponse.FromString,
                )


class DividerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DividerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=divider__pb2.DivideRequest.FromString,
                    response_serializer=divider__pb2.DivideResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.Divider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Divider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.Divider/Divide',
            divider__pb2.DivideRequest.SerializeToString,
            divider__pb2.DivideResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
