# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: divider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='divider.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'Z\002./',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdivider.proto\x12\x03\x61pi\"%\n\rDivideRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"/\n\x0e\x44ivideResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t2>\n\x07\x44ivider\x12\x33\n\x06\x44ivide\x12\x12.api.DivideRequest\x1a\x13.api.DivideResponse\"\x00\x42\x04Z\x02./b\x06proto3'
)




_DIVIDEREQUEST = _descriptor.Descriptor(
  name='DivideRequest',
  full_name='api.DivideRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='api.DivideRequest.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='api.DivideRequest.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=59,
)


_DIVIDERESPONSE = _descriptor.Descriptor(
  name='DivideResponse',
  full_name='api.DivideResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='api.DivideResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='api.DivideResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['DivideRequest'] = _DIVIDEREQUEST
DESCRIPTOR.message_types_by_name['DivideResponse'] = _DIVIDERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DivideRequest = _reflection.GeneratedProtocolMessageType('DivideRequest', (_message.Message,), {
  'DESCRIPTOR' : _DIVIDEREQUEST,
  '__module__' : 'divider_pb2'
  # @@protoc_insertion_point(class_scope:api.DivideRequest)
  })
_sym_db.RegisterMessage(DivideRequest)

DivideResponse = _reflection.GeneratedProtocolMessageType('DivideResponse', (_message.Message,), {
  'DESCRIPTOR' : _DIVIDERESPONSE,
  '__module__' : 'divider_pb2'
  # @@protoc_insertion_point(class_scope:api.DivideResponse)
  })
_sym_db.RegisterMessage(DivideResponse)


DESCRIPTOR._options = None

_DIVIDER = _descriptor.ServiceDescriptor(
  name='Divider',
  full_name='api.Divider',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='Divide',
    full_name='api.Divider.Divide',
    index=0,
    containing_service=None,
    input_type=_DIVIDEREQUEST,
    output_type=_DIVIDERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIVIDER)

DESCRIPTOR.services_by_name['Divider'] = _DIVIDER

# @@protoc_insertion_point(module_scope)
